name: ecomart
description: A Flutter e-commerce application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase (hanya core dan Firestore)
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5

  # State management dan localization
  provider: ^6.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Package untuk membuat ikon aplikasi kustom
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # Folder aset untuk gambar
  assets:
    - assets/images/

# Konfigurasi Launcher Icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ecomart.png"
  min_sdk_android: 21
